### PR TITLE
Fix various compilation errors in snippets

### PR DESCRIPTION
**Pull request by sqrrrl**
Fixes various broken files causing travis to fail. Not necessarily the final/desired form of things, just trying to get to a known good state.

### CODE REVIEW

**Comment by sqrrrl** [comment]
FYI - The travis failure was a transient error due to travis exhausting short term quota on downloading go packages.

**Comment by erickoledadevrel** [comment]
Re-assigning to @asrivas since she knows Go and I don't really.

**Comment by sqrrrl** [comment]
That makes two of us :)

**Comment by erickoledadevrel** [comment]
@asrivas - This has been waiting for a while. Can you PTAL?

**Pull request merged**
